name: Deploy to EC2 via ECR

on:
  push:
    branches: [feature/deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > ~/.npmrc
          echo "@dangol-dev:registry=https://npm.pkg.github.com/" >> ~/.npmrc

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} |
          docker login --username AWS --password-stdin ${{ secrets.DEV_ECR_REPOSITORY }}

      - name: Build Docker image
        run: |
          docker build -t next-app .
          docker tag next-app:latest ${{ secrets.DEV_ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.DEV_ECR_REPOSITORY }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_KEY }}
          script: |
            docker pull ${{ secrets.DEV_ECR_REPOSITORY }}:latest
            docker stop next-app || true && docker rm next-app || true
            docker run -d --name next-app -p 3000:3000 ${{ secrets.DEV_ECR_REPOSITORY }}:latest
