name: Deploy to EC2

on:
  push:
    branches: feature/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > ~/.npmrc
          echo "@dangol-dev:registry=https://npm.pkg.github.com/" >> ~/.npmrc

      - name: Setup Node.js & pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies & build with pnpm
        run: |
          pnpm install
          pnpm build

      - name: Create deployment package (zip)
        run: |
          zip -r app.zip . -x "node_modules/*" ".git/*"

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: 'app.zip'
          target: '/home/ubuntu/'

      - name: Remote SSH to deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu
            rm -rf app-backup
            mv app app-backup || true
            unzip -o app.zip -d app
            cd app
            pnpm install --prod
            pm2 restart next-app || pm2 start pnpm --name "next-app" -- start
