# name: Build and Deploy Real Docker Image to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Configure .npmrc
#         run: |
#           echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > .npmrc
#           echo "@dangol-dev:registry=https://npm.pkg.github.com/" >> .npmrc

#       - name: Build Docker image
#         run: |
#           docker build -t dangol-partner-center-real-app:latest .

#       - name: Save Docker image to tar file
#         run: |
#           docker save -o dangol-partner-center-real-app.tar dangol-partner-center-real-app:latest
#           chmod 664 dangol-partner-center-real-app.tar

#       - name: Copy image to EC2 via SCP
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.REAL_EC2_HOST }}
#           username: ubuntu
#           key: ${{ secrets.REAL_EC2_SSH_KEY }}
#           source: './dangol-partner-center-real-app.tar'
#           target: '/home/ubuntu/output'

#       - name: SSH into EC2 and deploy container
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.REAL_EC2_HOST }}
#           username: ubuntu
#           key: ${{ secrets.REAL_EC2_SSH_KEY }}
#           script: |
#             sudo docker stop dangol-partner-center-real-app
#             sudo docker rm dangol-partner-center-real-app
#             sudo docker image rm dangol-partner-center-real-app
#             sudo docker load -i ~/output/dangol-partner-center-real-app.tar
#             sudo docker run -d --name dangol-partner-center-real-app -p 3000:3000 dangol-partner-center-real-app
